export const GET_TIMELINE_OK = 'GET_TIMELINE_OK';
export const GET_TIMELINE_ERROR = 'GET_TIMELINE_ERROR';

export const TOGGLE_CARD = 'TOGGLE_CARD';
export const READ_LATER_CARD = 'READ_LATER_CARD';
export const REMOVE_CARD = 'REMOVE_CARD';
export const MOVE_CARD = 'MOVE_CARD';

export const GET_CONTENT_OK = 'GET_CONTENT_OK';
export const POPULATE_STORAGE = 'POPULATE_STORAGE';
